# Generated by Django 5.2.5 on 2025-08-17 06:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={'ordering': ['store', 'item']},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'brand')},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='brand_name_case_insensitive_unique', violation_error_message='Brand already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_case_insensitive_unique', violation_error_message='Category already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='item_name_case_insensitive_unique', violation_error_message='Item already exists (case insensitive match)'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='store_name_case_insensitive_unique', violation_error_message='Store already exists (case insensitive match)'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
    ]
